# .github/workflows/deploy.yml
name: Build and Deploy Blogger API Site

on:
  push:
    branches:
      - main # Workflow akan jalan saat ada push ke branch 'main'
      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Jalankan job di lingkungan Ubuntu

    steps:
    - name: Checkout kode sumber
      uses: actions/checkout@v4 # Mengambil kode dari repositori Anda

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests # <<< Pastikan baris ini ada

    - name: Jalankan skrip build Python
      run: python src/build.py

    - name: Deploy ke GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: main # Target branch untuk GitHub Pages
        force_orphan: true # Opsional, untuk pembersihan total branch gh-pages
