# .github/workflows/blogger_api.yml
name: Fetch Blogger Posts and Generate Index

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  fetch_posts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests Jinja2 beautifulsoup4 # Pastikan Jinja2 dan beautifulsoup4 terinstal

    - name: Run Blogger API script
      env:
        BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
        BLOG_ID: ${{ secrets.BLOG_ID }}
      run: |
        python main.py

    - name: Upload index.html as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-index-html
        path: index.html
